networks:
  work_net:


volumes:
  redhub_volume_articles:
  redhub_volume_users:
  redhub_volume_comments:


services:
  nginx:
    build:
      context: ./Core/Nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - work_net
    depends_on:
      - api-gateway

  api-gateway:
    build: 
      context: ./Core/Api-Gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    networks:
      - work_net
    depends_on:
      - user_service
      - article_service
      - comment_service
      - auth

  auth:
    build: 
      context: ./Core/Auth
    container_name: auth
    networks:
      - work_net
    ports:
      - 6005:50051
    depends_on:
      - user_service

  user_service:
    build:
      context: ./Core/UsersManageService
    container_name: user_service
    networks:
      - work_net
    ports:
      - "6001:50051"
    depends_on:
      psql_users:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123@psql_users:5432/redhub?sslmode=disable

  article_service:
    build:
      context: ./Core/ArticleManageService
    container_name: article_service
    networks:
      - work_net
    ports:
      - 6000:50051
    depends_on:
      psql_articles:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123@psql_articles:5432/redhub?sslmode=disable

  comment_service:
    build: 
      context: ./Core/CommentsManageService
    container_name: comment_service
    networks:
      - work_net
    ports:
      - "6004:50051"
    depends_on:
      psql_comments:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123@psql_comments:5432/redhub?sslmode=disable

  psql_articles:
    image: postgres:latest
    container_name: psql_articles
    ports:
      - "6100:5432"
    networks:
      - work_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: redhub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
    - redhub_volume_articles:/var/lib/postgresql/data

  psql_users:
    image: postgres:latest
    container_name: psql_users
    ports:
      - "6101:5432"
    networks:
      - work_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: redhub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
    - redhub_volume_users:/var/lib/postgresql/data

  psql_comments:
    image: postgres:latest
    container_name: psql_comments
    ports:
      - "6102:5432"
    networks:
      - work_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: redhub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
    - redhub_volume_comments:/var/lib/postgresql/data