version: '3'

networks:
  work_net:


services:
  api-gateway:
    build: 
      context: ./Api-Gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - work_net
      
  auth:
    build: 
      context: ./Auth
    container_name: auth
    ports:
      - "6000:50051"
    networks:
      - work_net
    depends_on:
      - user_service

  user_service:
    build: 
      context: ./UsersManageService
    container_name: user_service
    ports:
      - "6001:50051"
    networks:
      - work_net
    depends_on:
      - psql
    environment:
      - DATABASE_URL=postgres://postgres:gorm@psql:5432/postgres?sslmode=disable

  psql:
    image: postgres:latest
    container_name: psql
    ports:
      - "6002:5432"
    networks:
      - work_net
    environment:
      POSTGRES_PASSWORD: "gorm"