networks:
  work_net:


volumes:
  redhub_volume:


services:
  # nginx:
  #   build:
  #     context: ./Nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   networks:
  #     - work_net
  #   depends_on:
  #     - api-gateway

  api-gateway:
    build: 
      context: ./Api-Gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    networks:
      - work_net
    depends_on:
      - user_service
      - article_service
      - comment_service
      - auth

  auth:
    build: 
      context: ./Auth
    container_name: auth
    networks:
      - work_net
    ports:
      - 6005:50051
    depends_on:
      - user_service

  user_service:
    build: 
      context: ./UsersManageService
    container_name: user_service
    networks:
      - work_net
    ports:
      - "6001:50051"
    depends_on:
      - psql
    environment:
      - DATABASE_URL=postgres://postgres:123@psql:5432/redhub?sslmode=disable

  article_service:
    build: 
      context: ./ArticleManageService
    container_name: article_service
    networks:
      - work_net
    ports:
      - 6000:50051
    depends_on:
      - psql
    environment:
      - DATABASE_URL=postgres://postgres:123@psql:5432/redhub?sslmode=disable

  comment_service:
    build: 
      context: ./CommentsManageService
    container_name: comment_service
    networks:
      - work_net
    ports:
      - "6004:50051"
    depends_on:
      - psql
    environment:
      - DATABASE_URL=postgres://postgres:123@psql:5432/redhub?sslmode=disable

  psql:
    image: postgres:latest
    container_name: psql
    ports:
      - "6002:5432"
    networks:
      - work_net
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - redhub_volume:/var/lib/postgresql/data