env: "local"

usersStorageHost: "user_service"
usersStoragePort: 50051

articlesStorageHost: "article_service"
articlesStoragePort: 50051

commentsStorageHost: "comment_service"
commentsStoragePort: 50051

authHost: "auth"
authPost: 50051

api:
  port: 8080
  timeout: 5s